-- return {
-- 	{
-- 		"github/copilot.vim",
-- 		dependencies = {},
-- 		event = "VimEnter",
-- 		config = function()
-- 			vim.g.copilot_no_tab_map = false
-- 			vim.g.copilot_workspace_folders = { vim.fn.getcwd() }
-- 		end,
-- 	},
-- }
return {}
